### ISSUE TITLE
Beoplay stopped working

### ISSUE THREAD

**Issue by johnkirkster** [connectjunkie/homebridge-beoplay#25]
Hi, Beoplay plugin stopped working at my Homebridge setup. During bootup I get the following messages:

> [19/12/2021, 17:41:32] ====================
> [19/12/2021, 17:41:32] ERROR LOADING PLUGIN homebridge-beoplay:
> [19/12/2021, 17:41:32] Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/local/lib/node_modules/homebridge-beoplay/node_modules/got/dist/source/index.js from /usr/local/lib/node_modules/homebridge-beoplay/lib/BeoplayDevice.js not supported.
> Instead change the require of index.js in /usr/local/lib/node_modules/homebridge-beoplay/lib/BeoplayDevice.js to a dynamic import() which is available in all CommonJS modules.
>     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-beoplay/lib/BeoplayDevice.js:4:13)
>     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-beoplay/lib/BeoplayAccessory.js:3:23)
>     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-beoplay/index.js:3:26)
>     at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:132:77)
>     at PluginManager.initializeInstalledPlugins (/usr/local/lib/node_modules/homebridge/lib/pluginManager.js:64:30)
>     at Server.start (/usr/local/lib/node_modules/homebridge/lib/server.js:106:34)
> [19/12/2021, 17:41:32] ====================
> 
> [19/12/2021, 17:41:51] No plugin was found for the platform "Beoplay" in your config.json. Please make sure the corresponding plugin is installed correctly.

Any ideas what could be wrong?

**Comment by connectjunkie** [comment]
Can you let me know which version of the plug-in you have installed and which version of Node you're running?

**Comment by connectjunkie** [comment]
@johnkirkster Just pushed what should be a fixed version. Please let me know if this is working for you again

**Comment by johnkirkster** [comment]
@connectjunkie thanks, it did the trick
