### ISSUE TITLE
Unable to change volume

### ISSUE THREAD

**Issue by Anankin** [connectjunkie/homebridge-beoplay#26]
Hi I tested on several B&O devices with different type: TV and SmartSpeaker but on both I can't change volume with hard keys. On/off and changing sources works.

**Comment by connectjunkie** [comment]
You can change the volume with the hard keys using the TV integration, but that isn't within the Home app. 

You need to open the Control Center Remote and open the "TV" there. Then you can use the volume up/down hard keys. How HomeKit TVs show up on the iPhone/iPad is very non-intuitive.

**Comment by Anankin** [comment]
Aha ok. Implementation of volume into home app is not possible by homekit or you didn't find way how to implement?

**Comment by connectjunkie** [comment]
HomeKit support for speakers is currently very limited. 

Volume is easiest to set via the Fan or Bulb integrations (useful if you want to set via a scene or via Siri). Or you can set the volume in a HomeKit scene with the SmartSpeaker integration, just not within the Home app. See the README for details. 

Note, you can setup the same device with more than one type of integration, if needed.
