### ISSUE TITLE
Beovision Avant, power on not working

### ISSUE THREAD

**Issue by MikkelLindChr** [connectjunkie/homebridge-beoplay#7]
Hallo. I work with my Avant 55 tv. I you 0.2.0 version everthing works fine, but no i cant power off my tv. It do not send standby command.

"name": "Beovision Avant",
            "ip": "192.168.0.102",
            "type": "tv",
            "mode": "power",
            "on": "input",
            "default": 1,
            "inputs": [
                {
                    "name": "Apple TV",
                    "type": "HDMI",
                    "apiID": "HDMI1:7980.1860528.27418328@products.bang-olufsen.com"

**Comment by MikkelLindChr** [comment]
When i tab to standby i get this i homebridge: [Beovision Avant] Speaker is currently on

**Comment by connectjunkie** [comment]
OK - I can see the problem. I'll fix this and test and look to push a new version as soon as I can

**Comment by connectjunkie** [comment]
@MikkelLindChr This _should_ be fixed now. Can you upgrade the plugin and see if this now works as expected?
